export AWS_LOCAL_DEV_ACCESS_KEY_ID=your_local_dev_access_key_id
export AWS_LOCAL_DEV_SECRET_ACCESS_KEY=your_local_dev_secret_access_key
export AWS_LOCAL_DEV_REGION=your_local_dev_region

export AWS_STAGING_ACCESS_KEY_ID=your_staging_access_key_id
export AWS_STAGING_SECRET_ACCESS_KEY=your_staging_secret_access_key
export AWS_STAGING_REGION=your_staging_region

export AWS_INTEGRATION_SERVER_ACCESS_KEY_ID=your_integration_server_access_key_id
export AWS_INTEGRATION_SERVER_SECRET_ACCESS_KEY=your_integration_server_secret_access_key
export AWS_INTEGRATION_SERVER_REGION=your_integration_server_region

export AWS_PROD_ACCESS_KEY_ID=your_prod_access_key_id
export AWS_PROD_SECRET_ACCESS_KEY=your_prod_secret_access_key
export AWS_PROD_REGION=your_prod_region

export AWS_PRE_PROD_ACCESS_KEY_ID=your_pre_prod_access_key_id
export AWS_PRE_PROD_SECRET_ACCESS_KEY=your_pre_prod_secret_access_key
export AWS_PRE_PROD_REGION=your_pre_prod_region

export AWS_PARTNERS_ACCESS_KEY_ID=your_partners_access_key_id
export AWS_PARTNERS_SECRET_ACCESS_KEY=your_partners_secret_access_key
export AWS_PARTNERS_REGION=your_partners_region
