- import_playbook: common_setup_redis.yml

- hosts: ajprs-staging
  become: yes
  tasks:
    - name: Ensure Redis service is running
      service:
        name: redis
        state: started
        enabled: yes
