---
- name: Configure AWS CLI Profile
  hosts: localhost
  gather_facts: yes

  pre_tasks:
    - name: Generate input_aws_access_keys.yml from template
      template:
        src: ../../../../../input_aws_access_keys.yml.j2
        dest: /tmp/input_aws_access_keys.yml

  vars_files:
    - /tmp/input_aws_access_keys.yml

  tasks:
    - name: Define environment underscore variable
      set_fact:
        env_underscore: "{{ env | lower | replace('-', '_') }}"

    - name: Set AWS profile variables
      set_fact:
        aws_access_key_id: "{{ lookup('vars', 'aws_' + env_underscore + '_access_key_id') }}"
        aws_secret_access_key: "{{ lookup('vars', 'aws_' + env_underscore + '_secret_access_key') }}"
        aws_region: "{{ lookup('vars', 'aws_' + env_underscore + '_region') }}"

    - name: Configure AWS CLI profile (Access Key ID)
      command: >
        aws configure set aws_access_key_id {{ aws_access_key_id }} --profile ajprs-{{ env }}
    
    - name: Configure AWS CLI profile (Secret Access Key)
      command: >
        aws configure set aws_secret_access_key {{ aws_secret_access_key }} --profile ajprs-{{ env }}
    
    - name: Configure AWS CLI profile (Region)
      command: >
        aws configure set region {{ aws_region }} --profile ajprs-{{ env }}
